### ISSUE TITLE
automatically delete a favor when it reaches the expiration_date_time

### ISSUE THREAD

**Issue by samueljaval** [samueljaval/wes-favors-backend#9]

**Comment by alpiazza13** [comment]
Do we need to delete the favor at that point or can we just not show it in the frontend?

**Comment by samueljaval** [comment]
I guess we could but why overcrowd de database if we don't have to. If there's too much stuff in the database it can take longer to filter stuff out in the frontend.

**Comment by alpiazza13** [comment]
> I guess we could but why overcrowd de database if we don't have to. If there's too much stuff in the database it can take longer to filter stuff out in the frontend.

Yeah I agree about that but do we really want to be deleting favors from the database ever? Like don't we want to keep track of all favors requested/accepted for each user? I don't think we want each ID in those lists to point to nothing once its favor expires. Maybe an alternative would be to move them into a new collection - have one collection for current favors and one for expired favors?

**Comment by samueljaval** [comment]
oh yes I def agree with you
